-- Storage RLS policies for avatars and events buckets
-- Note: These policies are typically managed via the Supabase dashboard (Storage > Policies)
-- or via the management API, not via raw migrations (storage.objects is a system table).
-- 
-- To apply these policies manually via the Supabase dashboard:
-- 1. Go to Storage > Buckets > avatars > Policies
-- 2. Create INSERT policy "Users can upload own avatars"
--    - Allowed roles: authenticated
--    - MIME type: any
--    - Search path: avatars/
--    - Condition (optional): none
-- 3. Create SELECT policy "Users can read avatars"
--    - Allowed roles: authenticated
--    - Condition: none (allow all)
-- 4. Repeat for events bucket with path "events/"
--
-- Alternatively, use the Supabase CLI:
--   supabase postgres execute --file supabase/migrations/20251113_setup_storage_buckets.sql
--
-- For now, this is a placeholder migration. The actual RLS setup must be done via:
-- - Supabase Dashboard (recommended for simplicity), or
-- - Supabase management API with proper admin credentials

-- This migration intentionally does not execute storage.objects modifications
-- since those require ownership permissions not available in standard migrations.
-- See README or deployment docs for manual storage policy setup steps.
